# Generated by Django 5.2.9 on 2026-02-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('menu', '0002_dishoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='options',
            field=models.ManyToManyField(blank=True, to='menu.dishoption'),
        ),
    ]
