# Generated by Django 5.2.9 on 2026-02-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Кур’єр (+50 грн)'), ('pickup', 'Самовивіз')], max_length=20),
        ),
    ]
